apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-privileged-containers
spec:
  validationFailureAction: Enforce
  rules:
    - name: deny-privileged
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Deployment
      validate:
        message: >-
          Privileged containers are not allowed.
<<<<<<< HEAD
        anyPattern:
          - spec:
              containers:
                - securityContext:
                    privileged: "false"
          - spec:
              template:
                spec:
                  containers:
                    - securityContext:
                        privileged: "false"
=======
        pattern:
          spec:
            =(template):
              spec:
                containers:
                  - =(securityContext):
                      =(privileged): "false"
>>>>>>> 41e6728 (Create kyverno policies)
