# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-12"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "drive-ops-vm"
        vb.memory = "4096"
        vb.cpus = 2
    
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.network "private_network", ip: "192.168.56.10"

    # Port forwarding template
    # Client Gateway
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    # Driver Service
    config.vm.network "forwarded_port", guest: 8082, host: 8082, host_ip: "127.0.0.1"
    # Trip Service
    config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
    # PostgreSQL
    config.vm.network "forwarded_port", guest: 5432, host: 5432, host_ip: "127.0.0.1"
    # RabbitMQ AMQP
    config.vm.network "forwarded_port", guest: 5672, host: 5672, host_ip: "127.0.0.1"
    # RabbitMQ Management UI (Web UI)
     config.vm.network "forwarded_port", guest: 15672, host: 15672, host_ip: "127.0.0.1"

    config.vm.synced_folder "../..", "/vagrant", 
        type: "virtualbox",
        owner: "vagrant",
        group: "vagrant",
        mount_options: ["dmode=775,fmode=664"]

    config.vm.hostname = "drive-ops"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y python3 python3-pip linux-headers-$(uname -r) build-essential dkms
    SHELL


    config.vm.provision "shell", privileged: false, inline: <<-SHELL
        echo "Installing Ansible..."
        sudo apt-get update
        sudo apt-get install -y ansible
        
        echo "Installing community.docker collection..."
        ansible-galaxy collection install community.docker
        echo "Running Ansible playbook..."
        cd /vagrant/infra/ansible
        ansible-playbook -i inventory/localhost playbook.yaml
        #Trip service playbook
        ansible-playbook -i inventory/localhost trip-service-deploy.yaml
        echo ""
        echo "Provisioning complete!"
        echo ""
    SHELL

    config.vm.post_up_message = <<-MESSAGE
    ======================================
    Drive-Ops VM is ready!
    ======================================
    
    Services will be available at:
    - Client Gateway: http://localhost:8080
    - Driver Service: http://localhost:8082
    - Trip Service: http://localhost:8081
    
    Infrastructure:
    - RabbitMQ UI:    http://localhost:15672 (use credentials from your .env)
    - PostgreSQL:     localhost:5432 (use credentials from your .env)
    ======================================
    MESSAGE
end
