apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: driver-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UA-4697-DevOps/drive-ops.git
<<<<<<< HEAD
    targetRevision: v0.0.0-dev
    path: driver-service/charts/driver-service
    helm:
      valueFiles:
        - values-dev.yaml
=======
    targetRevision: HEAD
    path: driver-service/k8s
>>>>>>> ea3861c (feat: add driver-service ArgoCD Application for app-of-apps)
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
