apiVersion: v1
kind: ConfigMap
metadata:
  name: driver-service-config
  namespace: dev
  labels:
    app: driver-service
data:
  aws-region: "us-east-2"
  sqs-trip-created-url: "https://sqs.us-east-2.amazonaws.com/<AWS_ACCOUNT_ID>/trip-created-dev.fifo"
  sqs-driver-assigned-url: "https://sqs.us-east-2.amazonaws.com/<AWS_ACCOUNT_ID>/driver-assigned-dev.fifo"
  sqs-trip-completed-url: "https://sqs.us-east-2.amazonaws.com/<AWS_ACCOUNT_ID>/trip-completed-dev.fifo"
  client-gateway-url: "http://client-gateway.dev.svc.cluster.local:8080"
