apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-client.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web-client.labels" . | nindent 8 }}
    spec:
      containers:
        - name: web-client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          env:
            - name: DRIVER_SERVICE_URL
              value: {{ .Values.env.DRIVER_SERVICE_URL | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: {{ .Values.securityContext.privileged }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
