apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-client.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "web-client.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ .Values.service.portName }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  sessionAffinity: None
