replicaCount: 2

image:
  tag: "none"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  LOG_LEVEL: "warning"
  ENVIRONMENT: "prod"

serviceAccount:
  iamRoleArn: ""  # auto-populated by CI

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
