replicaCount: 2

image:
  tag: "none"  # updated ONLY via promotion PR

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

env:
  LOG_LEVEL: "warning"
  ENVIRONMENT: "prod"

serviceAccount:
  iamRoleArn: ""  # auto-populated by CI via aws sts

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

gateway:
  url: "http://client-gateway.client-gateway.svc.cluster.local:80"

sqs:
  tripCreatedUrl: "https://sqs.us-east-2.amazonaws.com/969283154407/trip-created-prod.fifo"
  driverAssignedUrl: "https://sqs.us-east-2.amazonaws.com/969283154407/driver-assigned-prod.fifo"
  tripCompletedUrl: "https://sqs.us-east-2.amazonaws.com/969283154407/trip-completed-prod.fifo"
