replicaCount: 1

image:
  tag: "none"  # auto-updated by CI via yq

autoscaling:
  enabled: false

env:
  LOG_LEVEL: "debug"
  ENVIRONMENT: "dev"

serviceAccount:
  iamRoleArn: ""  # auto-populated by CI via aws sts

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

gateway:
  url: "http://client-gateway.client-gateway.svc.cluster.local:80"

sqs:
  tripCreatedUrl: "https://sqs.us-east-2.amazonaws.com/969283154407/trip-created-dev.fifo"
  driverAssignedUrl: "https://sqs.us-east-2.amazonaws.com/969283154407/driver-assigned-dev.fifo"
  tripCompletedUrl: "https://sqs.us-east-2.amazonaws.com/969283154407/trip-completed-dev.fifo"
