replicaCount: 1

image:
  tag: "none"

autoscaling:
  enabled: false

env:
  LOG_LEVEL: "debug"
  ENVIRONMENT: "dev"

serviceAccount:
  iamRoleArn: ""  # auto-populated by CI

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
