apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-gateway-secrets
  namespace: client-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: client-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: drive-ops/dev/rds/credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: drive-ops/dev/rds/credentials
        property: password
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: drive-ops/dev/monitoring/discord
        property: url
