apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trip-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"  # Deploy after infrastructure (External Secrets, metrics-server, etc.)
spec:
  project: default
  source:
    repoURL: https://github.com/UA-4697-DevOps/drive-ops.git
    targetRevision: HEAD
    path: trip-service/charts/trip-service
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: trip-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
