replicaCount: 2

image:
  tag: v1.0.0

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

gateway:
  url: "http://client-gateway.client-gateway.svc.cluster.local:80"

sqs:
  tripCreatedUrl: "https://sqs.us-east-2.amazonaws.com/<ACCOUNT_ID>/trip-created-prod.fifo"
  driverAssignedUrl: "https://sqs.us-east-2.amazonaws.com/<ACCOUNT_ID>/driver-assigned-prod.fifo"
  tripCompletedUrl: "https://sqs.us-east-2.amazonaws.com/<ACCOUNT_ID>/trip-completed-prod.fifo"

database:
  url: ""  # Inject at deploy time via --set or external secrets