apiVersion: v1
kind: ConfigMap
metadata:
  name: client-gateway-config
  namespace: client-gateway
  labels:
    app: client-gateway
data:
  trip-service-url:    "http://trip-service.trip-service.svc.cluster.local"
  driver-service-url:  "http://driver-service.driver-service.svc.cluster.local"
  health-check-port: "8080"
  debug: "false"
