apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-gateway-sa
  namespace: client-gateway
  labels:
    app: client-gateway
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::969283154407:role/client-gateway-role"
