apiVersion: v1
kind: Secret
metadata:
  name: trip-service-secrets
  namespace: dev
  labels:
    app: trip-service
type: Opaque
stringData:
  db-url: "postgresql://<DB_USER>:<DB_PASSWORD>@<RDS_ENDPOINT>:5432/trip_db"
  sqs-trip-created-url: "https://sqs.us-east-2.amazonaws.com/<ACCOUNT_ID>/trip-created-dev.fifo"
  sqs-driver-assigned-url: "https://sqs.us-east-2.amazonaws.com/<ACCOUNT_ID>/driver-assigned-dev.fifo"
  sqs-trip-completed-url: "https://sqs.us-east-2.amazonaws.com/<ACCOUNT_ID>/trip-completed-dev.fifo"
