apiVersion: v1
kind: Service
metadata:
  name: trip-service
  namespace: dev
  labels:
    app: trip-service
    app.kubernetes.io/name: trip-service
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app: trip-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
  sessionAffinity: None
