{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "driver-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
data:
  aws-region: {{ .Values.config.awsRegion | quote }}
  sqs-trip-created-url: {{ .Values.config.sqsTripCreatedUrl | quote }}
  sqs-driver-assigned-url: {{ .Values.config.sqsDriverAssignedUrl | quote }}
  sqs-trip-completed-url: {{ .Values.config.sqsTripCompletedUrl | quote }}
  client-gateway-url: {{ .Values.config.clientGatewayUrl | quote }}
{{- end }}
