apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: { { .Values.database.secretName } }
  namespace: { { .Release.Namespace } }
  labels: { { - include "driver-service.labels" . | nindent 4 } }
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: { { .Values.database.secretName } }
    creationPolicy: Owner
  data:
    - secretKey: { { .Values.database.secretKey } }
      remoteRef:
        key: { { .Values.externalSecret.secretPath } }
        property: { { .Values.externalSecret.property } }
