{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.secret.databaseUrl | default "" | quote }}
{{- end }}
