{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.usernameKey }}: {{ .Values.secret.dbUsername | default "" | quote }}
  {{ .Values.database.passwordKey }}: {{ .Values.secret.dbPassword | default "" | quote }}
  {{ .Values.database.hostKey }}: {{ .Values.secret.dbHost | default "" | quote }}
  {{ .Values.database.dbNameKey }}: {{ .Values.secret.dbName | default "driver_db" | quote }}
{{- end }}
