#Golang migrate tool
FROM migrate/migrate:v4.19.0

# Copy migrations and wrapper script
COPY db/migrations /migrations
COPY run-migrations.sh /run-migrations.sh
RUN chmod +x /run-migrations.sh

ENTRYPOINT ["/run-migrations.sh"]
