{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "client-gateway.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "client-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  bot-token: {{ .Values.bot.token | quote }}
{{- end }}
