apiVersion: v1
kind: Service
metadata:
  name: {{ include "client-gateway.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "client-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "client-gateway.selectorLabels" . | nindent 4 }}
  ports:
  - name: {{ .Values.service.portName }}
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  sessionAffinity: None
