#!/bin/bash
set -euo pipefail

# Validate required environment variables (using :- to safely handle 'set -u')
if [ -z "${PGHOST:-}" ] || [ -z "${PGUSER:-}" ] || [ -z "${PGPASSWORD:-}" ] || [ -z "${S3_BUCKET_URI:-}" ] || [ -z "${ENV:-}" ]; then
  echo "Error: Missing required database, S3, or ENV environment variables."
  exit 1
fi

# Format the environment string (e.g., changing "prod-us" to "prod_us" if necessary)
ENV_NORM="${ENV//-/_}"

# Match the names generated by 01-init-rds-schema.sh
DATABASES=("drive_ops_${ENV_NORM}_trip" "drive_ops_${ENV_NORM}_driver")
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

echo "Starting database backups at $TIMESTAMP for environment: $ENV..."

for DB in "${DATABASES[@]}"; do
  echo "--> Processing database: $DB"
  BACKUP_FILE="${DB}_${TIMESTAMP}.sql.gz"
  
  # Dump the database and compress it
  # pipefail ensures that if pg_dump fails, the whole pipeline fails
  pg_dump -h "$PGHOST" -U "$PGUSER" -d "$DB" | gzip > "/tmp/$BACKUP_FILE"
  
  echo "--> Uploading $BACKUP_FILE to $S3_BUCKET_URI..."
  aws s3 cp "/tmp/$BACKUP_FILE" "$S3_BUCKET_URI/$BACKUP_FILE"
  
  rm "/tmp/$BACKUP_FILE"
  echo "--> Successfully backed up $DB."
done

echo "All database backups completed successfully!"
