apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: driver-service-external-secret
  namespace: dev
  labels:
    app: driver-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: driver-service-secret-store
    kind: SecretStore
  target:
    name: driver-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: drive-ops/dev/driver-service/config
        property: database_url
