apiVersion: v1
kind: Secret
metadata:
  name: driver-service-secrets
  namespace: dev
  labels:
    app: driver-service
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://<DB_USER>:<DB_PASSWORD>@<RDS_ENDPOINT>:5432/driver_db"
