apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: driver-service-secret-store
  namespace: dev
  labels:
    app: driver-service
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: driver-service-eso-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: driver-service-eso-sa
  namespace: dev
  labels:
    app: driver-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::969283154407:role/Training-drive-ops-dev-driver-service-eso-role
