apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trip-service-external-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: trip-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-username
      remoteRef:
        key: drive-ops/dev/rds/credentials
        property: username
    - secretKey: db-password
      remoteRef:
        key: drive-ops/dev/rds/credentials
        property: password
