apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "driver-service.name" . }}-config
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
data:
  aws-region: {{ .Values.aws.region | quote }}
  sqs-trip-created-url: {{ .Values.sqs.tripCreatedUrl | quote }}
  sqs-driver-assigned-url: {{ .Values.sqs.driverAssignedUrl | quote }}
  sqs-trip-completed-url: {{ .Values.sqs.tripCompletedUrl | quote }}
  client-gateway-url: {{ .Values.gateway.url | quote }}
