apiVersion: v1
kind: Secret
metadata:
  name: {{ include "driver-service.name" . }}-secrets
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
