apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "driver-service.name" . }}-external-secret
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ include "driver-service.name" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ include "driver-service.name" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: {{ .Values.externalSecret.secretPath }}
        property: database_url
