apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "driver-service.name" . }}-secret-store
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "driver-service.name" . }}-eso-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "driver-service.name" . }}-eso-sa
  labels:
    {{- include "driver-service.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.externalSecret.iamRoleArn }}
