apiVersion: v1
kind: ConfigMap
metadata:
  name: client-gateway-config
  namespace: dev
  labels:
    app: client-gateway
data:
  trip-service-url: "http://trip-service.dev.svc.cluster.local:8081"
  driver-service-url: "http://driver-service.dev.svc.cluster.local:8082"
  health-check-port: "8080"
  debug: "False"
