apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-gateway-secrets
  namespace: client-gateway
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: client-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: bot-token
      remoteRef:
        key: drive-ops/dev/client-gateway/bot
        property: token
