apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: driver-service-secrets
  namespace: driver-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: driver-service-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ .DB_USERNAME }}:{{ .DB_PASSWORD }}@{{ .DB_HOST }}/{{ .DRIVER_DB_NAME }}"
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: drive-ops/dev/rds/credentials
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: drive-ops/dev/rds/credentials
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: drive-ops/dev/driver-service
        property: RDS_ENDPOINT
    - secretKey: DRIVER_DB_NAME
      remoteRef:
        key: drive-ops/dev/driver-service
        property: DB_NAME
