apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: client-gateway
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  namespaceSelector:
    matchNames:
      - client-gateway
  selector:
    matchLabels:
      app: client-gateway
  jobLabel: app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s