apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: driver-service
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  namespaceSelector:
    matchNames:
      - driver-service
  selector:
    matchLabels:
      app: driver-service
  jobLabel: app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
